### ISSUE TITLE
Can we resolve other content types

### ISSUE THREAD

**Issue by OR13** [quartzjer/did-jwk#2]
Assuming this is meant to return `application/json` or  `application/did+json` by default.

I would be nice to be able to use did:jwk but get back CWKs when resolving as application/did+cbor

**Comment by quartzjer** [comment]
Hmm, I'll have to re-read CWK, I'm not sure there's an intended means for an automated transform, but if so I agree!

**Comment by quartzjer** [comment]
After re-reading [COSE_Key](https://datatracker.ietf.org/doc/html/rfc8152#section-7) there isn't any intent for an automated transform from a JWK.

Without such a standard to reference it would have to be defined from scratch, and I don't think this is the right place to tackle such a thing so I'm going to close this issue.

**Comment by OR13** [comment]
I guess it sorta makes sense that `did:jwk` might never support CBOR or YAML.
